### ISSUE TITLE
pulseaudio-control-increase fails

### ISSUE THREAD

**Issue by moritzschaefer** [flexibeast/pulseaudio-control#10]
While pulseaudio-control-decrease does what it should, calling pulseaudio-control-increase fails. I observed in the source code that the two functions are not at all similar. Is there a reason for that?

**Comment by flexibeast** [comment]
There is indeed: `-increase-volume` has to guard against the user increasing the volume without bound, something that might cause hardware (and maybe wetware!) problems. As far as i'm aware, there's not an analogous issue faced by `-decrease-volume`.

Is `-increase-volume` only failing in certain situations (e.g. when the existing volume is a certain value), or is it simply not working at all? And either way, are any errors or warnings displayed?

**Comment by Dragomundo** [comment]
Same thing happens for me too, everytime I try to increase the volume it says
<code>
Wrong type argument: stringp, nil
</code>
set volume works though so I guess I'll continue to use that when I need to increase the volume

**Comment by flexibeast** [comment]
@IanMDonaldson: Thanks for reporting this error message! Can you please set the variable `debug-on-error` to `t` and let me know which line of code the debugger lands on when you try to increase the volume?

**Comment by Dragomundo** [comment]
Here's the output of Backtrace

<code>
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
string-to-number(nil)
pulseaudio-control-increase-volume()
funcall-interactively(pulseaudio-control-increase-volume)
call-interactively(pulseaudio-control-increase-volume nil nil)
command-execute(pulseaudio-control-increase-volume)
</code>

LN numbers of the string-to-number are L266 through L288 inside of pulseaudio-control.el

**Comment by flexibeast** [comment]
Thanks. So the output of `pactl` is not in the format that my package is expecting. Can you please call the `eval-expression` command, enter `(pulseaudio-control--get-current-volume)` as the expression, and let me know the output?

(Also, what does `pactl --version` at the CLI report?)

**Comment by Dragomundo** [comment]
The output of eval-expression: (pulseaudio-control--get-current-volume) is
<code>
"Volume: front-left: 0 /   0% / -inf dB,   front-right: 0 /   0% / -inf dB"
</code>

As for pactl it is version 12.2 compiled and linked with libpulse 12.2.0

oh and also your comment gave me the idea to try it with different volumes and the error ONLY comes up with volume at 0%

**Comment by flexibeast** [comment]
Ah, thank you! My guess is that the problem is the `-inf`s as the decibel value; i'll modify the code to try to deal with this.

**Comment by flexibeast** [comment]
@moritzschaefer : i believe that this issue has now been [resolved](https://github.com/flexibeast/pulseaudio-control/commit/638a02b0b59cd9662abbbb9dc947d0fed115b72d) - could you please confirm?

**Comment by moritzschaefer** [comment]
Cool thanks! I think this is it!
