### ISSUE TITLE
Improve readability of regex code

### ISSUE THREAD

**Issue by flexibeast** [flexibeast/pulseaudio-control#13]
As suggested by @sarg in [this comment](https://github.com/flexibeast/pulseaudio-control/pull/12#issuecomment-478324304):

> I think that long regexes should be split into logical groups and commented heavily for future readers. I would also add example string that I'm trying to match with the regex.

**Comment by ghost** [comment]
@flexibeast Can we close this now that #20 was merged in?

**Comment by flexibeast** [comment]
Yes indeed - thanks for reminding me!
