### ISSUE TITLE
(pulseaudio-control-increase-volume) fails with German locale

### ISSUE THREAD

**Issue by dakling** [flexibeast/pulseaudio-control#15]
When using a German locale, `(pulseaudio-control-increase-volume)` fails with
`wrong type argument, stringp nil`. (At the same time, `(pulseaudio-control-decrease-volume)`works fine.)
This is probably due to pactl outputting the current volume with commas instead of points as the decimal separator.
Personally, I prefer a decimal point anyway, so I changed my system's locale to English - everything works fine now, but I still decided to report this edge case in case it is helpful.

**Comment by flexibeast** [comment]
Thanks for reporting this! Sorry for having taken so long to get back to you.

i certainly want things to work regardless of locale, and i've just pushed a change to that end - could you please test it and check if it works for you?

**Comment by dakling** [comment]
No worries, this was not urgent (for me at least) 

Everything is working fine now - Thanks!
