### ISSUE TITLE
Detect current sink/source

### ISSUE THREAD

**Issue by sarg** [flexibeast/pulseaudio-control#4]
It will be convenient if we have a variable with currently active sink/source. [This script]( https://github.com/graysky2/pulseaudio-ctl) script does it by grepping `pacmd list-sinks` output. I am not proficient with elisp yet. Could you please implement this feature?

**Comment by Ambrevar** [comment]
I don't know if this is related, but `pactl` also supports indexing with `@DEFAULT_SINK@`.
For instance, you could do the following:

```diff
-(defcustom pulseaudio-control-default-sink "0"
+(defcustom pulseaudio-control-default-sink "@DEFAULT_SINK@"
```

**Comment by sarg** [comment]
@Ambrevar thanks a lot. This special index resolves the issue. 

I have put this in my config and it works great.
```elisp
  (setq pulseaudio-control--current-sink "@DEFAULT_SINK@")
```
